name: Selenium Java Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout actions
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Chrome with extra capabilities
        uses: browser-actions/setup-chrome@1.4.0
        with:
          chrome-version: stable # Set Stable Version
          chrome-options: '--headless' # Run In Headless Mode

      - name: Build with Gradlew
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Run tests
        run: ./gradlew clean test # Run Test After Build Step


      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber report
          path: target/testing-reports.html